name: flutter_application_2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  fl_chart: ^0.66.2
  google_fonts: ^6.1.0
  model_viewer_plus: ^1.10.0
  flutter_3d_controller: ^2.3.0
  webview_flutter: ^4.0.0
  intl: ^0.19.0
  mqtt_client: ^10.0.1
  permission_handler: ^11.4.0 
  # THÊM DÒNG NÀY VÀO:
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Đã thêm phần assets ở đây
  assets:
    - assets/Bambo_House.glb
    - assets/index.html
    - assets/house_iso.png
    - assets/interact.js